default: &default
  adapter: mysql2
  host: localhost
  pool: 50
  port: 3306
  username: root
  password: 123

development:
  <<: *default
  database: Idea

test:
  <<: *default
  database: scraping_test

production:
  <<: *default
  database: scraping_production