# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ec6d441767d21e02dd7458ca0ec7b28a69640eeb6c98ef086d8a39ac2bf94223d3e4909a0fdaf0a7e26478d8216261506904206a974827e427ed22f0b77b0b

test:
  secret_key_base: 4914da627928c3ba07224617f8db97b4899a76982060fce0956846855a1cfb2b2ff7ad886689573060d62ae0d6d174e2abb5fcd3dab02642fe26f69e7bfd2095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
